[package]
name = "tauri-plugin-audio-recorder-android"
version = "0.1.8"
authors = [ "Mehmet Uysal" ]
description = "High-performance background audio recording plugin for Tauri 2.0 Android apps with Foreground Service and real-time amplitude support."
homepage = "https://github.com/HMUysal/tauri-plugin-audio-recorder-android"
repository = "https://github.com/HMUysal/tauri-plugin-audio-recorder-android"
license = "MIT"
keywords = ["tauri","tauri-plugin","android","audio-recorder","foreground-service"]
edition = "2021"
rust-version = "1.77.2"
exclude = ["/examples", "/dist-js", "/guest-js", "/node_modules"]
links = "tauri-plugin-audio-recorder-android"

[dependencies]
tauri = { version = "2.11.1" }
serde = "1.0"
thiserror = "2"

[build-dependencies]
tauri-plugin = { version = "2.6.1", features = ["build"] }
