"$schema" = "schemas/schema.json"

[[permission]]
identifier = "allow-stop"
description = "Enables the stop command."
commands.allow = ["stop"]

[[permission]]
identifier = "deny-stop"
description = "Denies the stop command."
commands.deny = ["stop"]